default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_food_site_dev
  username: project_food_site
  password: test123
  host: localhost

test:
  <<: *default
  database: project_food_site_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
