default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_food_site_dev
  username: project_food_site
  password: test123
  host: localhost

test:
  <<: *default
  database: project_food_site_test

production:
  primary: &primary_production
    <<: *default
    database: project_food_site_production
    username: project_food_site
    password: <%= ENV["PROJECT_FOOD_SITE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: project_food_site_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: project_food_site_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: project_food_site_production_cable
    migrations_paths: db/cable_migrate
